development:
  adapter: postgresql
  database: stack_overflow_development

test:
  adapter: postgresql
  database: stack_overflow_test

production:
  adapter: postgresql
  database: stack_overflow_production
